# Generated by Django 3.0.8 on 2020-08-04 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_title', models.CharField(max_length=300)),
                ('posts_writer', models.CharField(max_length=200)),
                ('posts_date', models.DateTimeField(verbose_name='date published')),
                ('posts_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer_title', models.CharField(max_length=300)),
                ('Answer_writer', models.CharField(max_length=200)),
                ('Answer_date', models.DateTimeField(verbose_name='date published')),
                ('Answer_votes', models.IntegerField(default=0)),
                ('Answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Posts')),
            ],
        ),
    ]
